[package]
authors = ["Reeze Xia <reeze.xia@gmail.com>"]
name = "memcached"
version = "0.0.0"

[lib]
name = "memcached"

[dependencies]
futures = "0.1.2"
tokio-core = "0.1.0"
bytes = "0.3.0"
log = "*"

